[workspace]
members = [
  "engine",
  "node",
  #"prover/poker/core",
  #"prover/poker/host",
  #"prover/poker/methods",
]
resolver = "2"

[patch.crates-io]
ark-ff = { git = "https://github.com/arkworks-rs/algebra" }
ark-ec = { git = "https://github.com/arkworks-rs/algebra" }
ark-poly = { git = "https://github.com/arkworks-rs/algebra" }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra" }
ark-bn254 = { git = "https://github.com/arkworks-rs/algebra" }
ark-ed-on-bn254 = { git = "https://github.com/arkworks-rs/algebra" }
zplonk = { path = "../uzkge/plonk"}
