[package]
name = "poker-host"
version = "0.1.0"
edition = "2021"

[dependencies]
poker-methods = { path = "../methods" }
serde = {version = "1.0", features = ["derive"]}
risc0-zkvm = { version = "0.19" }